openapi: 3.1.3

info:
  title: Dream-tracker Habit tracking app
  version: '1.0'

servers:
  - url: http://localhost:8080/api

tags:
  - name: habit
  - name: view
  - name: goal
  - name: category

paths:
  /habits:
    summary: Operations about habit
    post:
      tags:
        - habit
      summary: Create habit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Name of the new habit
                description:
                  type: string
                  description: Description of the new habit
                frequency:
                  type: string
                  description: Frequency of the habit
      responses:
        201:
          description: Habit correctly created
        400:
          description: Bad request
    get:
      tags:
        - habit
      summary: Get all the habits
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The unique identifier of the habit.
                    name:
                      type: string
                      description: The name of the habit.

        500:
          description: Internal server error

  /habits/{habit_id}:
    put:
      tags:
        - habit
      summary: Updates existing habit by id
      parameters:
        - in: path
          name: habit_id
          required: true
          schema:
            type: integer
          description: The unique identifier of the habit.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Name of the new habit
                description:
                  type: string
                  description: Description of the new habit
                frequency:
                  type: string
                  description: Frequency of the habit
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The unique identifier of the habit.
                  name:
                    type: string
                    description: The name of the habit.
        400:
          description: Bad Request - The request was invalid or cannot be served.
          content:
            application/json:
              schema:
                type: object
    delete:
      tags:
        - habit
      summary: Delete habit by id
      parameters:
        - in: path
          name: habit_id
          required: true
          schema:
            type: integer
          description: The unique identifier of the habit.
      responses:
        204:
          description: Habit properly deleted
        400:
          description: Bad Request - The request was invalid or cannot be served

    get:
      tags:
        - habit
      summary: Get habit by id
      parameters:
        - in: path
          name: habit_id
          required: true
          schema:
            type: integer
          description: The unique identifier of the habit.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The unique identifier of the habit.
                  name:
                    type: string
                    description: The name of the habit.
        400:
          description: Bad Request - The request was invalid or cannot be served.
          content:
            application/json:
              schema:
                type: object
  /habits/user/{user_id}:
    get:
      tags:
        - habit
      summary: Get all of users habits
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
          description: The unique identifier of the habit.
      responses:
        200:
          description: Success
  # it could be achieved by swinging left for -> true or right for false
  /habits/{habit_id}/status:
   post:
     tags:
       - habit
     summary: Creating new record in habit track schema with status(done/undone) depending on request body
     requestBody:
       required: true
       content:
         application/json:
           schema:
             type: object
             properties:
               active:
                 type: boolean

  /goals:
    post:
      tags:
        - goal
      summary: Create goal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Name of the new habit
                description:
                  type: string
                  description: Description of the new habit
                frequency:
                  type: string
                  description: Frequency of the habit
      responses:
        201:
          description: goal correctly created
        400:
          description: Bad request
    get:
      tags:
        - goal
      summary: Get all the goals
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        500:
          description: Internal server error
  /goals/user/{user_id}:
    get:
      tags:
        - goal
      summary: Get all the goals of specified user by id
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
          description: The unique identifier of the habit.
      responses:
        200:
          description: Success
        500:
          description: Internal server error
  /goals/{goal_id}:
    put:
      tags:
        - goal
      summary: Updates existing goal by id
      parameters:
        - in: path
          name: goal_id
          required: true
          schema:
            type: integer
          description: The unique identifier of the habit.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Name of the new habit
                description:
                  type: string
                  description: Description of the new habit
                frequency:
                  type: string
                  description: Frequency of the habit
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The unique identifier of the habit.
                  name:
                    type: string
                    description: The name of the habit.
        400:
          description: Bad Request - The request was invalid or cannot be served.
          content:
            application/json:
              schema:
                type: object
    delete:
      tags:
        - goal
      summary: Delete goal by id
      parameters:
        - in: path
          name: goal_id
          required: true
          schema:
            type: integer
          description: The unique identifier of the goal.
      responses:
        204:
          description: Goal properly deleted
        400:
          description: Bad Request - The request was invalid or cannot be served