import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx
import './globals.css';
import { AppProvider } from './AppContext';
import React from "react";
import {SiteFooter} from "@/app/nav/footer";

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
      <body>
      <AppProvider>
        {children}
      </AppProvider>
      </body>
      </html>
  );
}
