import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import './globals.css';
import { AppProvider } from './AppContext';
import React from "react";
import {ToastProvider} from "@/components/ui/toast";
import {Toaster} from "@/components/ui/toaster";

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
      <body>
      <ToastProvider>
         <AppProvider>
                 {children}
         </AppProvider>
      </ToastProvider>
      <Toaster/>
      </body>
      </html>
  );
}
